---
name: MobPlugin
author: IvanCraft623
main: IvanCraft623\MobPlugin\MobPlugin
version: 0.1.8
api: 5.6.0
description: "Implements Mobs like Vanilla!"
virions:
  - RICHMCBE/Pathfinder/v0.0.3
permissions:
  mobplugin.command.spawner.cancel:
    description: "Allows the user to spawn mobs"
    default: op

  mobplugin.command.spawner:
    description: "Allows the user to manage mob spawners"
    default: op
...